#include "stm8s.h"
#include "led_setup.h"
void GPIO_setup(void){
	GPIO_DeInit(GPIOC);
	GPIO_Init(GPIOC, (GPIO_PIN_3),
						GPIO_MODE_OUT_PP_HIGH_FAST);
	//GPIO_Init(GPIOC, (GPIO_PIN_4 ),
	//					GPIO_MODE_IN_PU_NO_IT);
						
	GPIO_DeInit(GPIOD);
	GPIO_Init(GPIOD, (GPIO_PIN_3 ),GPIO_MODE_IN_FL_NO_IT);
	//GPIO_Init(GPIOD, (GPIO_PIN_2 ),GPIO_MODE_IN_PU_NO_IT);
	GPIO_Init(GPIOD,(GPIO_PIN_4|GPIO_PIN_5|GPIO_PIN_6)
						,GPIO_MODE_OUT_PP_HIGH_FAST);
}
void clock_setup(void){
	CLK_DeInit();
						
	CLK_HSECmd(DISABLE);
	CLK_LSICmd(DISABLE);
	CLK_HSICmd(ENABLE);
	while(CLK_GetFlagStatus(CLK_FLAG_HSIRDY) == FALSE);
						
	CLK_ClockSwitchCmd(ENABLE);
	CLK_HSIPrescalerConfig(CLK_PRESCALER_HSIDIV1);
	CLK_SYSCLKConfig(CLK_PRESCALER_CPUDIV1);
						
	CLK_ClockSwitchConfig(CLK_SWITCHMODE_AUTO, CLK_SOURCE_HSI, 
	DISABLE, CLK_CURRENTCLOCKSTATE_ENABLE);
						
	CLK_PeripheralClockConfig(CLK_PERIPHERAL_ADC, ENABLE);
	CLK_PeripheralClockConfig(CLK_PERIPHERAL_UART1, ENABLE);
	CLK_PeripheralClockConfig(CLK_PERIPHERAL_TIMER1, ENABLE);
}

#define TIM1_PRESCALER_1 ((u16) 0x00)
void TIM1_setup(void){               
	TIM1_DeInit();
	//Init the period 

	TIM1_TimeBaseInit(TIM1_PRESCALER_1,TIM1_COUNTERMODE_UP,16000,0);
	// 1/frequency, count value 800, frequency=16M/8000=2kHZ
	
	TIM1_OC3Init(TIM1_OCMODE_PWM1, TIM1_OUTPUTSTATE_ENABLE, 
								TIM1_OUTPUTNSTATE_ENABLE,0xFFFF, 
								TIM1_OCPOLARITY_LOW, TIM1_OCNPOLARITY_HIGH,
								TIM1_OCIDLESTATE_SET,
								TIM1_OCNIDLESTATE_RESET);
							
	TIM1_Cmd(ENABLE);
	TIM1_CtrlPWMOutputs(ENABLE);
}

void UART1_setup(void){               
	UART1_DeInit();
	UART1_Init(115200, UART1_WORDLENGTH_8D, 
						UART1_STOPBITS_1 ,UART1_PARITY_NO, 
						UART1_SYNCMODE_CLOCK_DISABLE , UART1_MODE_TXRX_ENABLE);

	UART1_Cmd(ENABLE);
}

void ADC1_setup(void){               
	ADC1_DeInit();
	ADC1_Init(ADC1_CONVERSIONMODE_SINGLE,  
						ADC1_CHANNEL_2,  
						ADC1_PRESSEL_FCPU_D2 ,  
						ADC1_EXTTRIG_GPIO,  
						DISABLE,  
						ADC1_ALIGN_RIGHT ,  
						ADC1_SCHMITTTRIG_ALL ,  
						DISABLE); 
	ADC1_ExternalTriggerConfig(ADC1_EXTTRIG_GPIO,DISABLE); 

	ADC1_Cmd(ENABLE);
}
